name: Update README

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Show current contents of README.md before running script
        run: cat README.md

      - name: Run script
        run: |
          python trends_update.py
          echo "Script executed. Current state:"
          git status

      - name: Show current contents of README.md after running script
        run: cat README.md

      - name: Check for changes using git diff
        run: git diff

      - name: Check Git Status
        run: git status

      - name: Verify current branch
        run: git rev-parse --abbrev-ref HEAD

      - name: Check for changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Changes detected"
          else
            echo "No changes detected"
            exit 0
          fi
      
      - name: Add README.md to staging area
        run: git add README.md

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git commit -m 'Update README' || echo "No changes to commit."
          git push

      - name: Cleanup Git Cache
        run: |
          git gc --aggressive --prune=now
